name       : kinfocenter
version    : 5.24.2
release    : 79
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/kinfocenter-5.24.2.tar.xz : af5dd1af07e308c42f55d5c2ec472ab5b4ab67bef03d29545f9bc5e6d03ebeda
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
optimize   : lto
builddeps  :
    - pkgconfig(libusb-1.0)
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
rundeps    :
    - kirigami2
    - plasma-disks
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
patterns   :
    - main :
        - /usr/lib64/libKInfoCenterInternal.so
