name       : kinfocenter
version    : 5.10.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.3/kinfocenter-5.10.3.tar.xz : d3810c556196aece308406ceef762cfd0eb9241476e73eb84260b2e5cee72429
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - extra-cmake-modules
    - kcmutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpackage-devel
    - kservice-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
