name       : kinfocenter
version    : 5.13.5
release    : 23
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/kinfocenter-5.13.5.tar.xz : f4dfd9534758815b3801da615efc9baa57a24b00dc0d9c6e7c61d0f1c7902997
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - extra-cmake-modules
    - kcmutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpackage-devel
    - kservice-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
