name       : kinfocenter
version    : 5.16.4
release    : 39
source     :
    - https://origin.download.kde.org/stable/plasma/5.16.4/kinfocenter-5.16.4.tar.xz : 30e4df2d641c4faa385a718c772d893900eca99591ffee5787d6563fe5130426
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
