name       : kinfocenter
version    : 5.27.6
release    : 94
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.6/kinfocenter-5.27.6.tar.xz : cd96e9952cc8c73337dda0786d45f3f381ca5137f8eca5feee2209f63981901b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
optimize   : lto
builddeps  :
    - pkgconfig(libusb-1.0)
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
rundeps    :
    - aha
    - clinfo
    - kirigami2
    - plasma-disks
    - vulkan-tools
    - wayland-utils
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/icons/hicolor/128x128/apps/hwinfo.png
patterns   :
    - main :
        - /usr/lib64/libKInfoCenterInternal.so
