name       : kinfocenter
version    : 5.16.5
release    : 40
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/kinfocenter-5.16.5.tar.xz : e3bbc5e2baedf35dc8750c99e18c115b651f2665218a105c08177bc5250eb9b1
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
