name       : kinfocenter
version    : 5.21.5
release    : 68
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/kinfocenter-5.21.5.tar.xz : 715a871f6d761515d804049672d58f78cfc04fd8c5db645c489a940979a6f49c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
optimize   : lto
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - pkgconfig(x11)
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kwayland-devel
rundeps    :
    - kirigami2
    - plasma-disks
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
