name       : kinfocenter
version    : 5.22.2
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/kinfocenter-5.22.2.1.tar.xz : 34c630cb096700c5c77cbdf73b36de47dbaaf02719416896ac16fd2591ac1a50
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
optimize   : lto
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - pkgconfig(libusb-1.0)
    - pkgconfig(x11)
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kwayland-devel
rundeps    :
    - kirigami2
    - plasma-disks
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
