name       : kinfocenter
version    : 5.17.2
release    : 42
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.2/kinfocenter-5.17.2.tar.xz : 1691df791a609572fcf09f952b98baff0a51d950088e25e212710aaff9dc4e7e
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libpci)
    - pkgconfig(libraw1394)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
